### PR TITLE
Update region_MD.py

### PR DESCRIPTION
**Pull request by SergiuMir**
Included new type of numbers.
New number example:
062097063

### CODE REVIEW

**Comment by daviddrysdale** [comment]
Please raise metadata changes with the upstream [libphonenumber project](https://github.com/googlei18n/libphonenumber).

**Comment by SergiuMir** [comment]
Im' sorry, but I'm new on github and I don't know how to raise metadata
changes with the upstream libphonenumber project
https://github.com/googlei18n/libphonenumber. :(

**Comment by daviddrysdale** [comment]
If you feel like updating the [master metadata file](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml), they have [instructions](https://github.com/googlei18n/libphonenumber/wiki/ContributeToTheProject) on how to go about that.  But it might be easier to just [raise an issue](https://github.com/googlei18n/libphonenumber/issues/new) to let them know that Moldova has a new mobile number possibility (062...).  They will probably ask for a reference to confirm, though.

**Comment by SergiuMir** [comment]
I already raised an issue.
Thanks!

**Pull request closed without merging**
