### PR TITLE
Travis CI: Add the brand new Python 3.7 to the mix

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
Fascinating....  Build [fails on Python 3.7](https://travis-ci.org/daviddrysdale/python-phonenumbers/jobs/399675529#L503).  I can not see why.  [Porting to Python 3.7](https://docs.python.org/3/whatsnew/3.7.html#porting-to-python-3-7)

**Comment by daviddrysdale** [comment]
Some of the doctests can be a bit brittle to changes in Python internals, and so probably need to be made more lenient (cf. commit 40c85635c5777bc29debddea1da3302f89bffa19) or reorganized slightly.

**Comment by cclauss** [comment]
__re__ changes in Python 3.7: https://docs.python.org/3/whatsnew/3.7.html#re

**Comment by daviddrysdale** [comment]
Closing and re-opening to trigger a new Travis build now that commit d61d39519916cae95eca9cb0889820ba649ddafc is in.

**Comment by daviddrysdale** [comment]
Thanks!

**Pull request merged**
