### PR TITLE
Add the ‘566’ personal phone number prefix for US

### PR DESCRIPTION
**Pull request by hoxworth**

### CODE REVIEW

**Comment by daviddrysdale** [comment]
The metadata just tracks the [upstream project](https://code.google.com/p/libphonenumber/), so could you [raise this there instead](https://code.google.com/p/libphonenumber/issues/entry) please.

**Comment by hoxworth** [comment]
@daviddrysdale Fair enough - what is the process you follow for updating from upstream's PhoneNumberMetadata.xml? Do you periodically grab the most recent trunk `resources/PhoneNumberMetadata.xml`? The most recent version appears to have support for 566 (and 577) personal numbers, which would also satisfy this need..

**Comment by daviddrysdale** [comment]
I try to update as soon after upstream changes appear as I can; I'd hope to get to [r669](https://code.google.com/p/libphonenumber/source/detail?r=669) today as it's just a metadata update.  (Code updates sometimes need to wait for a larger block of my free time.)

**Comment by hoxworth** [comment]
Whoa, didn't notice that change just went out today! Thanks for the update!

**Pull request closed without merging**
