### PR TITLE
Adding area code checking for brazilian numbers

### PR DESCRIPTION
**Pull request by pappacena**
Hi!

In Brazil, there are area codes also for mobile phones. This pull request adds this case with some test cases.

### CODE REVIEW

**Comment by pappacena** [comment]
Sorry for so many commits... I was not familiar with the repo structure :-)

**Comment by jeanlmonteiro** [comment]
+1

**Comment by daviddrysdale** [comment]
Hi,

As this is an algorithmic change, rather than a Python-specific change, this would be best suggested to the upstream [libphonenumber](https://github.com/googlei18n/libphonenumber/) project -- the Python code tries to track the Java code pretty closely.  They're also the experts on whether it makes sense for a `MOBILE` number to be geographical (given that it's, well, mobile).

**Comment by pappacena** [comment]
Hi, @daviddrysdale ! Thanks for your reply!

I just sent them I pull request (https://github.com/googlei18n/libphonenumber/pull/989). Let's wait for their reply.

**Comment by daviddrysdale** [comment]
I'm going to close this out as it looks like the upstream project will handle at some point.

**Pull request closed without merging**
